### ISSUE TITLE
[Critical]  Prismatic Mac Osx Scaling Bug

### ISSUE THREAD

**Issue by domp** [woodenshark/Lightpack#39]
This really needs to be fixed as fast as possible. I just hooked my lightpack up to my Mac Pro with a 4k display and noticed that the leds are not displaying the colors correctly when Im selecting a display resolution of 1920x1080. However, it works fine with the normal display resolution of 3840x2160. (http://support.apple.com/kb/PH14388).

I've tried Prismatik 5.11.1 (from the lightpack website) and 5.11.2 from the github master branch, neither does work. I'm using Mac OS X 10.10 with a Samsung U28D590D connected via display port and one lightpack (10 leds), placed in an andromeda pattern.

Edit: I have taken some screens:

Works (normal display resolution of 3840x2160):
![true](https://cloud.githubusercontent.com/assets/1571388/4970462/6f9f3f90-6882-11e4-8e18-2bfb366e60b6.JPG)

Doesn't work (scaled display resolution of 1920x1080):
![false](https://cloud.githubusercontent.com/assets/1571388/4970467/81c80a12-6882-11e4-89fb-a751195ee932.JPG)

**Comment by e-yes** [comment]
Could you try this build: https://yadi.sk/d/Czx3pEbxdZToh
I'm not sure it will fix this issue, but I can't reproduce it on my side any way...

**Comment by domp** [comment]
I tried it, now the lighting is even more off center...

What if I set up a remote desktop connection to my mac, would it be possible for you to fix the issue then?

**Comment by e-yes** [comment]
Thank you, but I've tried already this option. Wouldn't work due to slow internet connection here:(
Any way, I'll try to borrow Mac next week and reproduce the issue.

**Comment by domp** [comment]
Got any luck with this?

**Comment by domp** [comment]
Also, Prismatik on windows 8.1 with a resolution of 3840x2160 and an interface scaling of 200% works flawless. It's just a bug with the mac os x version.

Besides that I think the biggest issue is the horribly inefficient screen grabbing method Prismatik uses. And then there are like a thousand small issues on github and google code that need to be fixed, including mine. The fact alone that everybody on windows uses ambibox instead of prismatik should tell you that this app really needs a major overhaul. I'd say you start fixing them now or atleast hire someone who can do it. And before you ask, yes I'm implying that you aren't capable of maintaining this repo. I'm sorry but this had to be said.

**Comment by e-yes** [comment]
You're clever guy. Now calculate a chance that I will spend my cash to rent Mac.

**Comment by domp** [comment]
Besides your horrible grammar, do the woodenshark guys actually pay you to maintain this repo? Just curious.

**Comment by e-yes** [comment]
Окей, буду использовать родной язык. Ты же полиглот. Осилишь?

**Comment by domp** [comment]
And now you even insulted me. Thanks, that will make it easier to get my refund on paypal.

**Comment by domp** [comment]
Nice try, but too late: https://web.archive.org/web/20150124084429/https://github.com/woodenshark/Lightpack/issues/39

**Comment by domp** [comment]
https://web.archive.org/web/20150124084429/https://github.com/woodenshark/Lightpack/issues/39

I can do this all day long man...
