### ISSUE TITLE
[Critical] Prismatic Mac Osx Scaling Bug #2

### ISSUE THREAD

**Issue by domp** [woodenshark/Lightpack#46]
See #39

**Comment by domp** [comment]
Oh man, paypal will love this
Thank you so much for making it so easy!

**Comment by e-yes** [comment]
If you want refund - contact their support. Don't behave like a baby with broken toy.
Good luck.

**Comment by domp** [comment]
Can you fully acknowledge that Prismatik is broken and because of that the Lightpack is not working for me? After you admit that, I'll stop.
