### ISSUE TITLE
Screen grabbing still not working on android.

### ISSUE THREAD

**Issue by BryceLK** [woodenshark/Lightpack#50]
I've been following various pieces of instructions I've found online as well as the information listed in https://github.com/woodenshark/Lightpack/issues/16

A workaround was provided and the issue was closed. My device is rooted and SuperSu permissions granted. I'm able to access the adb shell as root, however, when I enter the information provided, 

chown 0.0 /data/data/com.prismadroid.unity/prism-screenshot-server-16
chmod 755 /data/data/com.prismadroid.unity/prism-screenshot-server-16

I'm told that there is No such file or directory. This is not a problem in any part of the string until the "/prism-screenshot-server-16" is added. Please assist in resolving this.. Is it a directory that needs to be created somehow, or am I simply doing something incorrectly?

**Comment by e-yes** [comment]
You don't need to change permissions manually in latest version of Prismatik.
