### ISSUE TITLE
Prismatik crashes on Mint 17 (Ubuntu 14.04 based) Cinnamon 

### ISSUE THREAD

**Issue by derekdickerson** [woodenshark/Lightpack#54]
Got the device and of course it doesn't work and nothing on the Oses that it has issues with.

[   54.301252] prismatik[2847]: segfault at 20 ip 00007f04b8c82f50 sp 00007fff1836fea0 error 4 in libgtk-x11-2.0.so.0.2400.23[7f04b8c10000+42f000]
[   71.080706] prismatik[2855]: segfault at 20 ip 00007fe64894af50 sp 00007fff118027d0 error 4 in libgtk-x11-2.0.so.0.2400.23[7fe6488d8000+42f000]
[   92.954479] prismatik[2909]: segfault at 20 ip 00007fcc47532f50 sp 00007fffbed23130 error 4 in libgtk-x11-2.0.so.0.2400.23[7fcc474c0000+42f000]
[  161.332246] prismatik[3020]: segfault at 20 ip 00007fa80f40af50 sp 00007fff2d2fa4a0 error 4 in libgtk-x11-2.0.so.0.2400.23[7fa80f398000+42f000]
[  298.013405] prismatik[3417]: segfault at 20 ip 00007fe4e798af50 sp 00007fffe14a5740 error 4 in libgtk-x11-2.0.so.0.2400.23[7fe4e7918000+42f000]
[  313.107738] prismatik[3422]: segfault at 20 ip 00007f3a649b2f50 sp 00007fff75241970 error 4 in libgtk-x11-2.0.so.0.2400.23[7f3a64940000+42f000]
[  316.708786] prismatik[3426]: segfault at 20 ip 00007fb4b0baaf50 sp 00007fff84fb1760 error 4 in libgtk-x11-2.0.so.0.2400.23[7fb4b0b38000+42f000]
[  325.313965] prismatik[3432]: segfault at 20 ip 00007f4f64a0af50 sp 00007fff151de540 error 4 in libgtk-x11-2.0.so.0.2400.23[7f4f64998000+42f000]
[  348.506246] prismatik[3447]: segfault at 20 ip 00007f2a560a2f50 sp 00007fffa20f9ea0 error 4 in libgtk-x11-2.0.so.0.2400.23[7f2a56030000+42f000]

**Comment by derekdickerson** [comment]
it loaded once then never again

**Comment by e-yes** [comment]
Could you describe your problem properly:
What version/build do you use?
Have you tried this build: https://yadi.sk/d/_IHp5l6Cbej2a ?
Can you provide full backtrace and/or other useful logs and information?

**Comment by e-yes** [comment]
Duplicate to: https://github.com/woodenshark/Lightpack/issues/23
