### ISSUE TITLE
Prismatik 6.x: Add ability to select between backlighting colors

### ISSUE THREAD

**Issue by seltzered** [woodenshark/Lightpack#59]
Cool to see the redesigned Prismatik! I have some initial feedback. Most of my lightpack use is as computer monitor bias lighting - and switch between two 'day' and 'night' colors with f.lux.

In the new prismatik I noticed one can queue up to 5 colors for animation - but when you're not animating I'd like to make a request to be able to select between the colors. Currently the user can only change the colors or remove them - the color used for backlighting when not animated is always the first color.

![screen shot 2015-11-14 at 5 16 46 pm](https://cloud.githubusercontent.com/assets/297435/11166657/85f189c6-8af3-11e5-976b-9663e99fdec2.png)

**Comment by mofirouz** [comment]
I recommend creating a separate profiles for non-animating colour? In my use case, I have 3 profiles:
1. dynamic lighting
2. animation
3. constant backlight

**Comment by seltzered** [comment]
Thanks -- that works for me. Never realized what profiles were for.

**Comment by seltzered** [comment]
I seem to be having issues with the profiles feature. I created a 'day' and 'night' profile, restarted prismatik to see them in the menubar, and when alternating between the two the color stays stuck until I finally go back into the main prefs and change the color. This occurs regardless of whether I select the profile from the menubar or within the main preferences window. 

Also, there appears to be an issue where the user can select multiple profiles simultaneously. 

![screen shot 2015-11-16 at 3 11 25 pm](https://cloud.githubusercontent.com/assets/297435/11197810/c2434518-8c74-11e5-9f6a-3a18588d0ff5.png)

environment: Prismatik 6.0 on el capitan
