### ISSUE TITLE
Old lightpack (first rev, with miniUSB only) invalid USB descriptor

### ISSUE THREAD

**Issue by arcaine2** [woodenshark/Lightpack#77]
I have an old variant of Lightpack, bought years ago which was working just fine untill it stopped being detected by OS. After disassembly it looks like the fir rev, with miniUSB only, with 12 LEDs.

dmesg only shows:
[1132625.783436] usb 7-1: new full-speed USB device number 5 using uhci_hcd
[1132625.818483] usb 7-1: device descriptor read/8, error -61
[1132625.954486] usb 7-1: device descriptor read/8, error -61
[1132626.060136] usb usb7-port1: unable to enumerate USB device

Windows claims the desciptor is invalid and clasifies the devices with VID_0000&PID_0005.
I tried entering firmware update mode by pressing the button on the board while plugging the USB but it's still the same.

Any idea what died on it? Could this be AT90USB162 issue and replacing and flashing with new firmware could help?

**Comment by e-yes** [comment]
I think this is only related to cable OR USB connector - when they're worn - you can face such an issue.

**Comment by arcaine2** [comment]
Already tried different cable and different PC, same problem. After disassembly the USB connector looks perfect, not corroded or loose etc. I had the set assembled in place since i bought it, never moved it so this should not be a soldering issue. I already ordered both AT90USB162 and USB6B1 to check.

**Comment by arcaine2** [comment]
Problem solved. Replacing AT90USB162 made it detected as DFU device properly. Flashing correct firmware and fixing soldering for couple elements around the MCU to make LEDs working made it fully working again. Guess microcontroller went bad for some reason after all.
